modLoader = "javafml"
loaderVersion = "[31.2,)"

license = "GPL version 3 or any later version"
issueTrackerURL = "https://github.com/DenDragon23/LovecraftPlus/issues"

[[mods]]
modId = "lovecraftplus"
displayName = "Lovecraft Plus"
version = "${version}"
description = """
This mod takes inspiration from the writer H.P Lovecraft.
Here, we make all sorts of new mobs and dimensions where these monsters come from.
"""
displayURL = "https://github.com/DenDragon23/LovecraftPlus"

credits = "Haunted Chest, PutoPug, Cheese God, Conzilla and TheOnlyTails"
authors = "LovecraftPlus Team"

[[dependencies.lovecraftplus]]
modId = "forge"
versionRange = "[31.2,)"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.lovecraftplus]]
modId = "minecraft"
versionRange = "[1.15.2]"
mandatory = true
ordering = "NONE"
side = "BOTH"
