modLoader = "javafml"
loaderVersion = "[36,)"

license = "GPL version 3 or any later version"
issueTrackerURL = "https://github.com/Team-Cryptic-Cosmos/Cryptic-Cosmos/issues"

[[mods]]
modId = "crypticcosmos"
displayName = "Cryptic Cosmos"
version = "1.16.5-1.3.16-beta"
description = """
This mod shows a creative 3 new dimensions with all sorts of bizzare blocks, mobs, and features! Giving you amazing new realms to explore :D
"""
displayURL = "https://github.com/Team-Cryptic-Cosmos/Cryptic-Cosmos/"
logoFile = "logo.png"

credits = "Haunted Chest#0323, Sediment Fellow on Discord, EggOff, LudoCrypt#6191, TheArty, Realz#5075, Jooji, and TheOnlyTails"
authors = "Cryptic Cosmos Team"

[[dependencies.crypticcosmos]]
modId = "forge"
versionRange = "[36,)"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.crypticcosmos]]
modId = "minecraft"
versionRange = "[1.16.5,)"
mandatory = true
ordering = "NONE"
side = "BOTH"

[[dependencies.crypticcosmos]]
modId = "geckolib"
versionRange = "[3,)"
mandatory = false
ordering = "NONE"
side = "BOTH"
