name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: LootTables Version
      description: What version of Cryptic Cosmos are you running?
      placeholder: e.g. v1.3.17-beta
    validations:
      required: true
  - type: input
    attributes:
      label: Forge Version
      description: What version of Forge are you using?
      placeholder: e.g. v36.1.32
    validations:
      required: true
  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - v1.16.5
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (generated JSONs, code snippets) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      render: markdown
