blank_issues_enabled: true
contact_links:
  - name: Any Questions?
    url: https://discord.com/users/645291351562518542
    about: Have any questions? Reach me on Discord!
  - name: More Contact Info
    url: https://theonlytails.com/
    about: Can't use discord? Try some other contact methods!
